fun main(args: Array<String>) {
    println("Every time you feel like you can't go on")
    println("Remember that you're not alone")
    println("We all have been here and we all have known")
    println("The darkness and the unknown")
    println("But don't be afraid to reach out your hand")
    println("You'll find a friend who will understand")
    println("The binding ties that truly never end")
    println("Will light the way throughout your journey")
    println("")
    println("Chorus:")
    println("It's all about heart and soul")
    println("That's what takes us where we need to go")
    println("It's all about heart and soul")
    println("It's what makes us strong and whole")
    println("")
    println("Sometimes life can make us feel so small")
    println("The bigger picture can be hard to see")
    println("And when the pressure's on, it can be hard to stand tall")
    println("But don't give in, believe in you and me")
    println("We have each other to keep us from falling")
    println("With courage and determination")
    println("Our dreams will come alive and be calling")
    println("Our true destination")
    println("")
    println("Chorus:")
    println("It's all about heart and soul")
    println("That's what takes us where we need to go")
    println("It's all about heart and soul")
    println("It's what makes us strong and whole")
    println("")
    println("Bridge:")
    println("We can have hope when times are tough")
    println("We can have strength when times are rough")
    println("We can go on, even when we don't have enough")
    println("We can make it through, if we don't give up")
    println("")
    println("Chorus:")
    println("It's all about heart and soul")
    println("That's what takes us where we need to go")
    println("It's all about heart and soul")
    println("It's what makes us strong and whole")
    println("")
    println("It's all about heart and soul")
    println("That's what takes us where we need to go")
    println("It's all about heart and soul")
    println("It's what makes us strong and whole")    
}